commented

diff --git a/Jenkinsfile_bkp b/Jenkinsfile_bkp
--- a/Jenkinsfile_bkp
+++ b/Jenkinsfile_bkp
@@ -6,12 +6,17 @@ pipeline{
     environment {
         docker_registry = 'iamroyalreddy/fusion-be'
         DOCKERHUB_CREDENTIALS = credentials('docker-credentials')
-        DEV_INSTANCE_IP= ''
+        SONAR_SCANNER_HOME = tool name: 'sonarqube'
     }
     options {
         timeout(time: 1, unit: 'HOURS')
         disableResume()
         disableConcurrentBuilds()
+        timestamps()
+    }
+    parameters {
+        booleanParam(name: 'CodeAnalysisDependencyCheck', defaultValue: false, description: 'is it required Code Analysis and Dependency Check')
+        choice(name: 'DeployToStage', choices: ['yes', 'no'], description: 'is it required Deploy to stage')
     }
     stages{
         stage('Build and Package'){
@@ -20,36 +25,49 @@ pipeline{
             }
         }
 
-        stage('OWASP Dependency Check'){
-            steps {
-                dependencyCheck additionalArguments: '''
-                    --scan \'./\' 
-                    --out \'./\'  
-                    --format \'ALL\' 
-                    --disableYarnAudit \
-                    --prettyPrint''',  nvdCredentialsId: 'NVD-API_KEY', odcInstallation: 'OWASP-DepCheck-10'
+        // stage('Code Analysis and Testing'){
+        //     when {
+        //         expression{
+        //             params.CodeAnalysisDependencyCheck == true
+        //         }
+        //     }
+        //     parallel{
+        //         stage('OWASP Dependency Check'){
+        //             steps {
+        //                 dependencyCheck additionalArguments: '''
+        //                     --scan \'./\' 
+        //                     --out \'./\'  
+        //                     --format \'ALL\' 
+        //                     --disableYarnAudit \
+        //                     --prettyPrint''',  nvdCredentialsId: 'NVD-API_KEY', odcInstallation: 'OWASP-DepCheck-10'
 
-                dependencyCheckPublisher failedTotalCritical: 1, pattern: 'dependency-check-report.xml', stopBuild: false
-            }
-        }
+        //                 dependencyCheckPublisher failedTotalCritical: 1, pattern: 'dependency-check-report.xml', stopBuild: false
+        //             }
+        //         }
 
-        stage ("SAST - SonarQube") {
-            // currently skip test cases
-            steps {
-                script {
-                    withSonarQubeEnv(installationName: 'sonarqube', credentialsId: 'sonar-credentials') {
-                    sh '''
-                        mvn clean verify sonar:sonar -DskipTests \
-                            -Dsonar.projectKey=fusion-be \
-                            -Dsonar.projectName='fusion-be' \
-                            -Dsonar.host.url=http://3.87.22.97:9000 \
-                            -Dsonar.token=sqp_d51fa944280fed04f49882fd38efd69313c2708a
-                    '''
-                    }
-                }
-            }
-        }
-
+        //         stage ("SAST - SonarQube") {
+        //             // currently skip test cases
+        //             steps {
+        //                 script {
+        //                     withSonarQubeEnv('sonarqube') {
+        //                         withCredentials([string(credentialsId: 'sonar-credentials', variable: 'SONAR_TOKEN')]){
+        //                             withEnv(["PATH+SONAR=$SONAR_SCANNER_HOME/bin"]) {
+        //                                 sh '''
+        //                                     mvn clean verify sonar:sonar -DskipTests \
+        //                                         -Dsonar.projectKey=fusion-be \
+        //                                         -Dsonar.projectName='fusion-be' \
+        //                                         -Dsonar.host.url=$SONAR_HOST_URL \
+        //                                         -Dsonar.token=$SONAR_TOKEN
+        //                                 '''
+        //                             }
+        //                         }
+        //                     }
+        //                 }
+        //             }
+        //         }
+        //     }
+        // }
+        
         stage('containerization') {
             steps {
                 script{
@@ -114,45 +132,70 @@ pipeline{
             }       
         }
 
-        stage('Deploy - AWS EC2') {
-            steps {
-                script{
-                     // Fetch AWS instance IP
-                    withAWS(credentials: 'aws-fusion-dev-deploy', region: 'us-east-1') {
-                        DEV_INSTANCE_IP = sh(
-                            script: "aws ec2 describe-instances --query 'Reservations[].Instances[].PublicIpAddress' --filters Name=tag:Name,Values=dev-deploy --output text",
-                            returnStdout: true
-                        ).trim()
-                    }
-                    sshagent(['dev-deploy-ec2-instance']) {
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ec2-user@${DEV_INSTANCE_IP} "
-                                echo "Cleaning up old containers..."
-                                docker ps -aq | xargs -r docker rm -f
-                                echo "Running new Docker container..."
-                                docker run -d -p 8080:8080 ${docker_registry}:${GIT_COMMIT}
-                            "
-                        """
-                    }
-                    
+        stage('Deploy to Development') {
+            when {
+                expression { 
+                    params.DeployToStage == 'yes'
                 }
-            }   
-        }
+            }
+            environment {
+                DEV_STAGE_INSTANCE_IP= ''
+            }
+            stages {
+                stage('initialize-Dev-Stage Instance') {
+                    steps{
+                        dir('/var/lib/jenkins/workspace/fusion/Fusion-Backend/terraform'){
+                            sh '''
+                                set -e
+                                echo "Initializing Terraform..."
+                                terraform init -reconfigure
+                                echo "Applying Terraform configuration..."
+                                terraform apply --auto-approve
+                            '''
+                        }
+                    }
+                }
+                stage('Deploy - Dev-Stage Instance') {
+                    steps {
+                        script{
+                            // Fetch AWS instance IP
+                            withAWS(credentials: 'aws-fusion-dev-deploy', region: 'us-east-1') {
+                                DEV_STAGE_INSTANCE_IP = sh(
+                                    script: "aws ec2 describe-instances --query 'Reservations[].Instances[].PublicIpAddress' --filters Name=tag:Name,Values=DevelopmentBackendServer --output text",
+                                    returnStdout: true
+                                ).trim()
+                            }
+                            sshagent(['dev-deploy-ec2-instance']) {
+                                sh """
+                                    ssh -o StrictHostKeyChecking=no ec2-user@${DEV_STAGE_INSTANCE_IP} "
+                                        // echo "Cleaning up old containers..."
+                                        // docker ps -aq | xargs -r docker rm -f
+                                        echo "Running new Docker container..."
+                                        docker run -d -p 8080:8080 ${docker_registry}:${GIT_COMMIT}
+                                    "
+                                """
+                            }
+                            
+                        }
+                    }   
+                }
 
-        stage('Integration Testing - AWS EC2') {
-            steps {
-               sh 'sleep 200s'
-               withAWS(credentials: 'aws-fusion-dev-deploy', region: 'us-east-1') {
-                    sh  '''
-                        sh integration_test.sh
-                    '''
+                stage('Integration Testing in Development') {
+                    steps {
+                    sh 'sleep 150s'
+                    withAWS(credentials: 'aws-fusion-dev-deploy', region: 'us-east-1') {
+                            sh  '''
+                                sh integration_test.sh
+                            '''
+                        }
+                    }
                 }
             }
         }
     }
 
-        post { 
-            always { 
+    post { 
+        always { 
                 junit allowEmptyResults: true, stdioRetention: '', testResults: 'dependency-check-junit.xml' 
                 junit allowEmptyResults: true, stdioRetention: '', testResults: 'trivy-image-CRITICAL-results.xml'
                 junit allowEmptyResults: true, stdioRetention: '', testResults: 'trivy-image-MEDIUM-results.xml'            
@@ -161,22 +204,22 @@ pipeline{
                 publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: true, reportDir: './', reportFiles: 'trivy-image-MEDIUM-results.html', reportName: 'Trivy Image Medium Vul Report', reportTitles: '', useWrapperFileDirectly: true])
                 echo "\033[34mJob completed. Cleaning up workspace...\033[0m"
                 deleteDir()
+            }    
+        success {
+            echo "\033[33mPipeline completed successfully. Performing success actions...\033[0m"
+            // Add additional actions here if needed, like sending success notifications
             }
-            success {
-                echo "\033[33mPipeline completed successfully. Performing success actions...\033[0m"
-                // Add additional actions here if needed, like sending success notifications
-            }
-            failure { 
-                echo "\033[35mPipeline failed. Triggering failure response...\033[0m"
-                // send notification
-            }
-            unstable {
-                echo "\033[34mPipeline marked as unstable. Reviewing issues...\033[0m"
-                // Send notification or take action for unstable builds, if needed
-            }
-            aborted {
-                echo "\033[33mPipeline was aborted. Clearing any partial artifacts...\033[0m"
-                // Any specific actions for aborted jobs
-            }
+        failure { 
+            echo "\033[35mPipeline failed. Triggering failure response...\033[0m"
+            // send notification
         }
+        unstable {
+            echo "\033[34mPipeline marked as unstable. Reviewing issues...\033[0m"
+            // Send notification or take action for unstable builds, if needed
+        }
+        aborted {
+            echo "\033[33mPipeline was aborted. Clearing any partial artifacts...\033[0m"
+            // Any specific actions for aborted jobs
+        }    
+    }
 }
